[package]
name = "riscv_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
iset = "0.1.1"
byteorder = "1.4.3"
risky = "0.3.0"
rustc-hash = "1.1.0"
