[package]
name = "rambo"
version = "0.0.1"
authors = [ "Artem Borisovsky <bytefu@gmail.com>" ]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."

[[bin]]
name = "rambo"

[dependencies]
getopts = "0.2"
itertools = "0.6"
num = "0.1.37"
