[package]
name = "rambo"
version = "0.3.3"
authors = [ "Artem Borisovsky <bytefu@gmail.com>" ]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."
edition = '2018'

[[bin]]
name = "rambo"

[dependencies]
getopts = "0.2.18"
itertools = "0.8.0"
num-bigint = "0.2.2"
num-traits = "0.2.6"
petgraph = "0.4.13"
termcolor = "1.0.4"
libc = "0.2.50"
strum = "0.15.0"
strum_macros = "0.15.0"
elapsed = "0.1.2"
once_cell = "0.1.8"
number_prefix = "0.3.0"
stable-vec = { git = "https://github.com/burjui/stable-vec", rev = "c660fc50bfb6d553bd56d74032ef77573d8b2803" }
