[package]
name = "rambo"
version = "0.3.7"
authors = [ "Artem Borisovsky <bytefu@gmail.com>" ]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."
edition = '2018'

[[bin]]
name = "rambo"

[dependencies]
riscv = { path = "riscv" }
getopts = "0.2.21"
itertools = "0.8.2"
petgraph = "0.4.13"
termcolor = "1.0.5"
libc = "0.2.66"
elapsed = "0.1.2"
number_prefix = "0.3.0"
bitflags = "1.2.1"
risky = "0.2.3"
smallvec = "1.0.0"
derive_deref = "1.1.0"
bimap = "0.4.0"
byteorder = "1.3.2"
rvsim = "0.2.1"
ckb-vm = "0.18.1"
bytes = "0.4.2"

[profile.release]
debug = true
