[[bin]]
name = "rambo"

[package]
name = "rambo"
version = "0.3.7"
authors = ["Artem Borisovsky <bytefu@gmail.com>"]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."
edition = "2018"

[dependencies]
getopts = "0.2.21"
itertools = "0.9.0"
petgraph = "0.5.1"
termcolor = "1.1.0"
libc = "0.2.80"
elapsed = "0.1.2"
number_prefix = "0.4.0"
bitflags = "1.2.1"
smallvec = "1.4.2"
derive_deref = "1.1.1"
bimap = "0.5.2"
byteorder = "1.3.4"
rvsim = "0.2.1"
ckb-vm = "0.19.2"
bytes = "0.6.0"
bincode = "1.3.1"
risky = "0.3.0"

[dependencies.riscv]
git = "ssh://git@github.com/burjui/riscv.git"
tag = "v0.1.0"

[dependencies.rambo-riscv]
git = "ssh://git@github.com/burjui/rambo-riscv"
tag = "v0.1.2"

[profile.release]
debug = true
