[package]
name = "rambo"
version = "0.1.2"
authors = [ "Artem Borisovsky <bytefu@gmail.com>" ]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."
edition = '2018'

[[bin]]
name = "rambo"

[dependencies]
getopts = "0.2"
itertools = "0.7.8"
num-bigint = "0.2.0"
num-traits = "0.2.5"
petgraph = "0.4.12"
termcolor = "1.0.4"
libc = "0.2.43"
lazy_static = "1.2.0"
variant_count = "1.0.0"
num_enum = "0.1.1"
elapsed = "0.1.2"
regex = "1.0.6"

[features]
dump_ssa = []
