[package]
name = "rambo"
version = "0.3.7"
authors = [ "Artem Borisovsky <bytefu@gmail.com>" ]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."
edition = '2018'

[[bin]]
name = "rambo"

[dependencies]
getopts = "0.2.19"
itertools = "0.8.0"
petgraph = "0.4.13"
termcolor = "1.0.4"
libc = "0.2.55"
elapsed = "0.1.2"
once_cell = "0.2.0"
number_prefix = "0.3.0"
stable-vec = "0.3.2"
bitflags = "1.0.4"
risky = "0.2.3"
smallvec = "0.6.9"
derive_deref = "1.0.2"
bimap = "0.3.1"
copy_in_place = "0.2.0"
riscv = { path = "riscv" }
byteorder = "*"
rvsim = "*"

[profile.release]
debug = true
