[package]
name = "rambo"
version = "0.3.7"
authors = ["Artem Borisovsky <bytefu@gmail.com>"]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."
edition = '2018'

[[bin]]
name = "rambo"

[dependencies]
riscv = { git = "ssh://git@github.com/burjui/riscv.git" }
rambo-riscv = { git = "ssh://git@github.com/burjui/rambo-riscv.git", rev = "cd04a7f59f87fe08d426eebc9cc7f5a4c3b2a7f5" }
getopts = "0.2.21"
itertools = "0.9.0"
petgraph = "0.5.0"
termcolor = "1.1.0"
libc = "0.2.68"
elapsed = "0.1.2"
number_prefix = "0.3.0"
bitflags = "1.2.1"
risky = "0.2.3"
smallvec = "1.2.0"
derive_deref = "1.1.0"
bimap = "0.4.0"
byteorder = "1.3.4"
rvsim = "0.2.1"
ckb-vm = "0.19.1"
bytes = "0.5.4"
bincode = "1.2.1"

[profile.release]
debug = true
