[package]
name = "rambo"
version = "0.3.2"
authors = [ "Artem Borisovsky <bytefu@gmail.com>" ]
description = "Compiler for a toy programming language Rambo, written in Rust just for fun, i.e. with no practical purpose in mind."
edition = '2018'

[[bin]]
name = "rambo"

[dependencies]
getopts = "0.2.18"
itertools = "0.8.0"
num-bigint = "0.2.2"
num-traits = "0.2.6"
petgraph = "0.4.13"
termcolor = "1.0.4"
libc = "0.2.49"
strum = "0.13.0"
strum_macros = "0.13.0"
elapsed = "0.1.2"
once_cell = "0.1.8"
